### ISSUE TITLE
Add continuous integration via Github Actions

### ISSUE THREAD

**Issue by IgorPolyakov** [IlyaDovzhenko/spring-pet-clinic#23]
**что** - гитхаба, недавно завезла actions, на них можно сдеать полноценный CI
**зачем** - на каждый коммит будел делаться сборка проекта (и прогонятся тесты, если они есть), также эта штука является актуальной инструкцией для сборки проекта
**профит** понимание работы actions сделает тебя более востребованным на рынке труда)

**Comment by IlyaDovzhenko** [comment]
> **что** - гитхаба, недавно завезла actions, на них можно сдеать полноценный CI
> **зачем** - на каждый коммит будел делаться сборка проекта (и прогонятся тесты, если они есть), также эта штука является актуальной инструкцией для сборки проекта
> **профит** понимание работы actions сделает тебя более востребованным на рынке труда)

Согласен, убедил, позалипаю завтра как это сделать)
